### PR TITLE
Add custom bootloader example

### PR DESCRIPTION
**Pull request by i4ki**
Simple custom bootloader. 

It loads the operating system in a configured address and checks for a valid magic number in there. Additionally, it set the A20 line before jump to kernel code.

People, take a look if makes sense.
/cc @c0defellas/osdev

### CODE REVIEW

**Comment by geyslan** [comment]
Here `make` and `make test` run beautifully. I would consider the use of **nash** terminal. Even though it's a fantastic project, its syntax differs from the commonly recognized. As the project purpose is to combine code and tutorials on osdev subject what do you think of using **bash** to simplify the hassle of scripting to everyone?

**Comment by i4ki** [comment]
Good point @geyslan 

I've no problem if someone wants to add a bash version of the script. It's very simple (125 loc), easy to port.

But I think the script should be little and well explained (step-by-step) in the README because it's not something unimportant in this case, it's the core of why this works. If it works, and is explained, then I don't know why it should be written in a mainstream shell.

Someone trying to understand a bootloader can get most help reading here:
https://github.com/c0defellas/osdev/pull/2/files#diff-ae493a25d2e32dae232bbd64b9a7f273R19
than trying to understand a obscure bash syntax...

But this is something we need to discuss. I prefer use our own tools to avoid the script not working on some environments... For example, the script in question uses `dd` but the option `seek_bytes` isn't available in older GNU dd, and to build in the travis-ci I needed to upgrade de machine to ubuntu trusty... 
I'll create my own `dd`[1] soon to avoid such problems.

I used my own version of `fdisk` too, because `gnu fdisk` was designed in the 80s for interactive use only and doesn't work reading input from scripts... 
I have use cases like below:

``` sh
fdisk mbr -create -bootdisk boot.o /dev/sda
fdisk mbr -app-part 1 -fstype linux -start-chs 0 1 0 -end-chs 63 255 1000
fdisk data -part 1 -data ./partition-data.dump
```

We can learn a lot creating our own tools too...

Anyway, I'm open to port the script for bash if you think worth the effort.

1: https://github.com/tiago4orion/enzo/issues/8

**Comment by geyslan** [comment]
@tiago4orion I got your point about `nash` and it's ok. There's no need to add bash version then. What I must to emphasize is that recreating all building environment misleads the osdev (kernel) goal _per si_. As an example we would have to create our own versions of `wc`, `cut` and `tr` too, focusing to compartmentalize all the tools. https://github.com/c0defellas/osdev/blob/add-custom-bootloader-example/bootloaders/custom/make.sh#L39

But if that (to create a complete unique environment) is the goal, I vote on the migration of all the tools to this repository in the path `/tools`.

**Comment by i4ki** [comment]
Create a modern set of command line tools is my long term goal. I like the idea of osdev repo being self sustained  (everything you need to build is here), but I use this tools (fdisk, dd, ps, etc) outside osdev subject. 

Today, I'm writing the tools in Go in the repository [enzo](https://github.com/tiago4orion/enzo) for personal needs. Moving it to osdev repo could generate unneeded noise (issues and PR's not related to osdev).

The motivation for write the tools in Go are:
1. I like Go;
2. Easy to share
   - `go get <repo>/...` to download
   - Binaries are static by default (I can copy the binary between machines and just work)

If you do not have problems of tools being written in Go, we can create a repo inside c0defellas to maintain it there. 

Cheers

**Comment by geyslan** [comment]
You are right, it's better let the noise from tools repos outside. enzo seems to be a great project. I'll take a look at its issue list.

Cheers.

**Pull request merged**
